name: Update Flight Price

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub UI
  schedule:
    # Runs at 1 AM UTC every day
    - cron: '0 1 * * *'

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull remote changes before running script
        # This step is critical to prevent the rejected push error.
        run: git pull origin main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script to update flight data
        run: python flight_checker.py
        env:
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add flights_data.json
          git commit -m "Update flight price data via scheduled action" || echo "No changes to commit"
          git push
